name: Docker CI

on: [push]
#  release:
#    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Login to DockerHub Registry
              run: echo ${{ GITHUB_TOKEN }} | docker login --u ${{ GITHUB_ACTOR }} --password-stdin docker.pkg.github.com
            - name: Get the version
              id: vars
              run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
            - name: Build the tagged Docker image
              run: docker build . --file dockerfiles/Dockerfile_r-ver_3.6.2 --tag docker.pkg.github.com/noamross/rocker-versioned/r-ver:3.6.2
            - name: Push the tagged Docker image
              run: docker push docker.pkg.github.com/noamross/rocker-versioned/r-ver:3.6.2

